version: "3.9"  # optional since v1.27.0
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: gateway
    ports:
      - "8080:8080"
    links:
      - name_service
    environment:
      - NAME_SERVICE=http://name_service:8080
  name_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: name_service
    ports:
      - "8081:8080"
